Remove use of deprecated CKA_SECONDARY_AUTH
Compilation failed with:
src/ck_attribute_smart.cpp:111:8: error: use of undeclared identifier 'CKA_SECONDARY_AUTH'
  111 |                 case CKA_SECONDARY_AUTH:
      |                      ^
1 error generated.

because updated pkcs11.h now contains:
 /* Deprecated */
 #ifdef PKCS11_DEPRECATED
 #define CKA_ECDSA_PARAMS 0x00000180UL
 #define CKA_SECONDARY_AUTH 0x00000200UL
 #define CKA_AUTH_PIN_FLAGS 0x00000201UL
 #endif